<a href="https://colab.research.google.com/github/gunjanak/Pytorch_Course/blob/main/10_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = '/content/drive/MyDrive/Colab Notebooks/Python_Course/PyTorch_Course/uci-news-aggregator.csv'

In [3]:
df = pd.read_csv(path,encoding='latin-1')

In [4]:
len(df)

422419

In [5]:
# Count data from each genre
genre_counts = df['CATEGORY'].value_counts()

print(genre_counts)

e    152469
b    115967
t    108344
m     45639
Name: CATEGORY, dtype: int64


In [6]:
import plotly.express as px

In [7]:
# Create a bar plot using Plotly
fig = px.bar(x=genre_counts.index, y=genre_counts.values, labels={'x':'Genre', 'y':'Count'},
             title='Data Count from Each Genre')
fig.show()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
# Split the data into training and testing sets, keeping the ratio of categories the same
df2,_ = train_test_split(df, test_size=0.9, stratify=df['CATEGORY'])


In [10]:
len(df2)

42241

In [11]:
# Count data from each genre
genre_counts = df2['CATEGORY'].value_counts()

print(genre_counts)

e    15247
b    11596
t    10834
m     4564
Name: CATEGORY, dtype: int64


In [12]:
# Add a new column 'Genre_Num' with numerical representation using cat.codes
df2['CATEGORY_Num'] = df2['CATEGORY'].astype('category').cat.codes

# Display the DataFrame with numerical representation of genres
df2

ID                                              TITLE  \
247112  247558  Paul McCartney still ill, cancels South Korea ...   
141231  141567    Easter delivery: SpaceX shipment arrives at ISS   
325488  325948  Indiana home care funding doubled from 2002 to...   
184091  184427  The Walt Disney Company Beats on EPS and Reven...   
386642  387102  Fox is rejected in making unsought initial off...   
...        ...                                                ...   
280779  281239  Neil Patrick Harris Leaving Hedwig and the Ang...   
13906    13907                       Greenland Is Losing More Ice   
199830  200266        Kellogg settles Kashi food labeling lawsuit   
328278  328738  Kim Kardashian Shows Leg in High-Necked Black ...   
394261  394780           Microsoft under antitrust probe in China   

                                                      URL  \
247112  http://www.news-sentinel.com/apps/pbcs.dll/art...   
141231  http://www.ctvnews.ca/sci-tech/easter-delivery...   
325488  http://posttrib.suntimes.com/news/28325807-418...   
184091  http://www.dividend.com/news/2014/the-walt-dis...   
386642  http://www.staradvertiser.com/business/2014071...   
...                                                   ...   
280779  http://www.gossipcop.com/neil-patrick-harris-l...   
13906   http://www.thealmagest.com/greenland-is-losing...   
199830  http://www.examiner.com/article/kellogg-settle...   
328278  http://www.usmagazine.com/celebrity-style/news...   
394261  http://thepeninsulaqatar.com/business/internat...   

                       PUBLISHER CATEGORY                          STORY  \
247112             News Sentinel        e  dD_F96KX2Lm75AMVa_Sup55GB0B8M   
141231                  CTV News        t  dhX07Hl8r32k-oMN9vTxyA7aqWuAM   
325488              Post-Tribune        m  ddoCDwcVGhjq2vMZjnSbBJY8OtWZM   
184091     Dividend.com \(blog\)        b  dEznTp4zoY6kvXMiDQBsZ6XZvJxYM   
386642  Honolulu Star-Advertiser        b  dMElbuCt8WnYaeM7R5FNMSjx8irwM   
...                          ...      ...                            ...   
280779                 GossipCop        e  dV5Tqv7Xoj-aHpMQAh1-iAj4nL3IM   
13906               The Almagest        t  dpBHooDWKTXM0yMu77lW-S8DuG0OM   
199830              Examiner.com        b  dBxHiGAbnZnOFHMxilMqLBX4bnb7M   
328278               Us Magazine        e  d4MOFzOuKg94N2MA64sqob0e87SvM   
394261         Peninsula On-line        t  d-mbL8_DqBYvEdMBqoh-6GQ42xlLM   

                      HOSTNAME      TIMESTAMP  CATEGORY_Num  
247112   www.news-sentinel.com  1400940386155             1  
141231          www.ctvnews.ca  1398001503543             3  
325488   posttrib.suntimes.com  1403875495743             2  
184091        www.dividend.com  1399430801549             0  
386642  www.staradvertiser.com  1405613188962             0  
...                        ...            ...           ...  
280779       www.gossipcop.com  1402689096423             1  
13906      www.thealmagest.com  1395061143789             3  
199830        www.examiner.com  1399686880704             0  
328278      www.usmagazine.com  1403934481007             1  
394261   thepeninsulaqatar.com  1406644121301             3  

[42241 rows x 9 columns]

In [13]:
df3 = df2[['TITLE','CATEGORY','CATEGORY_Num']]

In [14]:
df3.head()

TITLE CATEGORY  \
247112  Paul McCartney still ill, cancels South Korea ...        e   
141231    Easter delivery: SpaceX shipment arrives at ISS        t   
325488  Indiana home care funding doubled from 2002 to...        m   
184091  The Walt Disney Company Beats on EPS and Reven...        b   
386642  Fox is rejected in making unsought initial off...        b   

        CATEGORY_Num  
247112             1  
141231             3  
325488             2  
184091             0  
386642             0

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(df3['TITLE'],df3['CATEGORY_Num'],random_state=0)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(min_df=5,ngram_range=(1,3)).fit(X_train)
#len(vect.get_feature_names())
X_train_vectorized = vect.transform(X_train)

In [34]:
X_train_vectorized[0][0]

<1x14948 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression()
model.fit(X_train_vectorized,y_train)
predictions = model.predict(vect.transform(X_test))
accuracy = model.score(vect.transform(X_test), y_test)
print(accuracy)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



0.9032288609033235


In [19]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import accuracy_score

In [20]:
class NewsClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NewsClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out


In [21]:
# Instantiate the model, define loss function and optimizer
input_size = X_train_vectorized.shape[1]
hidden_size = 128
num_classes = 4  # Assuming there are 4 categories
model = NewsClassifier(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [22]:
# Convert data to PyTorch tensors
X_train_tensor = torch.tensor(X_train_vectorized.toarray(), dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)

In [23]:
X_test_vectorized = vect.transform(X_test)

In [24]:
# Convert data to PyTorch tensors
X_test_tensor = torch.tensor(X_test_vectorized.toarray(), dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# Training loop
num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)
    loss.backward()
    optimizer.step()
    _, predicted = torch.max(outputs.data, 1)
    accuracy = accuracy_score(y_train_tensor.numpy(), predicted.numpy())
    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {loss.item()}, Train Accuracy: {accuracy}')



    # Calculate accuracy and confusion matrix
    model.eval()
    with torch.no_grad():
        outputs_test = model(X_test_tensor)
        _, predicted = torch.max(outputs_test.data, 1)
        accuracy = accuracy_score(y_test_tensor.numpy(), predicted.numpy())
        cm = confusion_matrix(y_test_tensor.numpy(), predicted.numpy())
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}, Accuracy: {accuracy}')


In [27]:
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[2535  140    2  181]
 [  72 3694    1   57]
 [ 287  232  505  117]
 [ 306  169    5 2258]]


#Using GRU

In [28]:
class NewsGRU(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NewsGRU, self).__init__()
        self.hidden_size = hidden_size
        self.gru = nn.GRU(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out, _ = self.gru(x)
        out = out[:, -1, :]  # Take the last output of the sequence
        out = self.fc(out)
        return out


In [29]:
input_size = X_train_vectorized.shape[1]
hidden_size = 1024
num_classes = 4  # Number of categories
model = NewsGRU(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [31]:
num_epochs = 10
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train_tensor.unsqueeze(1))  # Add a dimension for the sequence
    loss = criterion(outputs, y_train_tensor)
    loss.backward()
    optimizer.step()

    # Evaluation on the test set
    model.eval()
    with torch.no_grad():
        outputs_test = model(X_test_tensor.unsqueeze(1))
        _, predicted = torch.max(outputs_test.data, 1)
        accuracy = accuracy_score(y_test_tensor.numpy(), predicted.numpy())
        cm = confusion_matrix(y_test_tensor.numpy(), predicted.numpy())
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item()}, Accuracy: {accuracy}')
        print('Confusion Matrix:')
        print(cm)


Epoch [1/10], Loss: 1.386025309562683, Accuracy: 0.5407631853044219
Confusion Matrix:
[[  84 1744    0 1030]
 [   1 3730    0   93]
 [   1  859    0  281]
 [   1  840    0 1897]]
Epoch [2/10], Loss: 1.3681930303573608, Accuracy: 0.5990909951709118
Confusion Matrix:
[[ 948 1662    0  248]
 [   5 3806    0   13]
 [  17 1059    0   65]
 [  34 1131    0 1573]]
Epoch [3/10], Loss: 1.3504042625427246, Accuracy: 0.6271186440677966
Confusion Matrix:
[[1384 1327    0  147]
 [   6 3811    0    7]
 [  33 1072    0   36]
 [  81 1229    0 1428]]
Epoch [4/10], Loss: 1.332170009613037, Accuracy: 0.6419846605435091
Confusion Matrix:
[[1606 1128    0  124]
 [  10 3809    0    5]
 [  52 1063    0   26]
 [ 124 1249    0 1365]]
Epoch [5/10], Loss: 1.3131778240203857, Accuracy: 0.652779092888931
Confusion Matrix:
[[1724 1021    0  113]
 [  12 3807    0    5]
 [  67 1050    0   24]
 [ 150 1225    0 1363]]
Epoch [6/10], Loss: 1.293216347694397, Accuracy: 0.6613957011646624
Confusion Matrix:
[[1799  956    0 