<a href="https://colab.research.google.com/github/gunjanak/Pytorch_Course/blob/main/1_Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import

In [1]:
import torch

In [2]:
torch.__version__


'2.1.0+cu121'

#Declaration of Tensors

In [ ]:
#Basic 1-dimension Tensor
x = torch.Tensor([5])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
print(x)

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1])
The dimension of x is: 1
tensor([5.])


In [ ]:
#2 dimensional tensor
x = torch.Tensor([[5]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
print(x)

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1, 1])
The dimension of x is: 2
tensor([[5.]])


In [ ]:
#3 dimensional tensor
x = torch.Tensor([[[5]]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
print(x)

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1, 1, 1])
The dimension of x is: 3
tensor([[[5.]]])


In [ ]:
x = torch.Tensor([1,1,1])
y = torch.Tensor([[1,1,1],[2,2,2],[3,3,3]])
z = torch.Tensor([[[1,1,1],[2,2,2],[3,3,3]],
                  [[4,4,4],[5,5,5],[6,6,6]],
                  [[7,7,7],[8,8,8],[9,9,9]]])

In [ ]:
print(f"The dimension of x is {x.ndim} and the size of x is {x.size()}\n")
print(f"The dimension of y is {y.ndim} and the size of y is {y.size()}\n")
print(f"The dimension of z is {z.ndim} and the size of z is {z.size()}\n")

The dimension of x is 1 and the size of x is torch.Size([3])

The dimension of y is 2 and the size of y is torch.Size([3, 3])

The dimension of z is 3 and the size of z is torch.Size([3, 3, 3])



#item()

In [ ]:
x = torch.Tensor([5])
print(x.item())
print(type(x.item()))

5.0
<class 'float'>


In [ ]:
x = torch.Tensor([5,6,5,5])
print(x.item())
print(type(x.item()))

RuntimeError: a Tensor with 4 elements cannot be converted to Scalar

In [ ]:
x = torch.Tensor([[5,5,5,5],[9,6,3,8]])
print(x[1][0].item())
print(type(x[1][0].item()))

9.0
<class 'float'>


#Zero, Identity and Linspace

In [ ]:
#zero
v =torch.zeros(3,3)
print(v)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#Identity
I = torch.eye(2,2)
print(I)

tensor([[1., 0.],
        [0., 1.]])


In [ ]:
#Ones
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x = torch.ones_like(I)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
I = torch.eye(4,4)
print(I)
x = torch.ones_like(I)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
x = torch.linspace(0,100,11)
print(x)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])


In [ ]:
#Initialize Tensor with a range of value
v = torch.arange(5)
print(v)

tensor([0, 1, 2, 3, 4])


In [ ]:
v = torch.arange(0,5,step=1)
print(v)

tensor([0, 1, 2, 3, 4])


In [ ]:
v = torch.arange(0,5,step=0.5)
print(v)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000])


In [ ]:
#log scale tensor
v = torch.logspace(start=-2,end=2,steps=5)
print(v)

tensor([1.0000e-02, 1.0000e-01, 1.0000e+00, 1.0000e+01, 1.0000e+02])


In [ ]:
v = torch.logspace(start=-2,end=2,steps=9)
print(v)

tensor([1.0000e-02, 3.1623e-02, 1.0000e-01, 3.1623e-01, 1.0000e+00, 3.1623e+00,
        1.0000e+01, 3.1623e+01, 1.0000e+02])


In [ ]:
#Initialize a ByteTensor
c = torch.ByteTensor([0,1,1,0])
print(c)

tensor([0, 1, 1, 0], dtype=torch.uint8)


In [ ]:
c = torch.ByteTensor([0.2,1,1,0])
print(c)

tensor([0, 1, 1, 0], dtype=torch.uint8)


In [ ]:
c = torch.ByteTensor([0,112,1,0])
print(c)

tensor([  0, 112,   1,   0], dtype=torch.uint8)


In [ ]:
c = torch.ByteTensor([0,15.9,1,0])
print(c)

tensor([ 0, 15,  1,  0], dtype=torch.uint8)


#Random Generator

In [ ]:
#uniform distribution between 0 and 1
x = torch.rand(4)
print(x)

tensor([0.8312, 0.7189, 0.3876, 0.0401])


In [ ]:
x = torch.rand(3,3)
print(x)

tensor([[0.5344, 0.8753, 0.8489],
        [0.5057, 0.8878, 0.7557],
        [0.3316, 0.1569, 0.5757]])


In [ ]:
x = torch.rand(3,3,3)
print(x)

tensor([[[0.8601, 0.4088, 0.5499],
         [0.7819, 0.0087, 0.2703],
         [0.1014, 0.3473, 0.6304]],

        [[0.5429, 0.0798, 0.5550],
         [0.0196, 0.1250, 0.4448],
         [0.4950, 0.1484, 0.5202]],

        [[0.4114, 0.6008, 0.8080],
         [0.5353, 0.9532, 0.2007],
         [0.6162, 0.9044, 0.4603]]])


In [ ]:
#torch.randint(min,max,(size))
x = torch.randint(1,6,(2,2))
print(x)

tensor([[4, 5],
        [3, 5]])


In [ ]:
x = torch.randint(1,6,(1,1))
print(x)

tensor([[2]])


In [ ]:
#The following function returns a tensor with a random number from a normal distribution
#with a mean 0 and a variance of 1
x = torch.randn(2,2)
x

tensor([[-0.6024,  0.0728],
        [-0.7875,  1.0391]])

In [ ]:
#when mean and std are given
#torch.normal(mean,std,size)
x = torch.normal(2,3,(2,2))
print(x)

tensor([[ 2.1590, -3.5929],
        [ 4.9878,  2.5244]])


In [ ]:
x = torch.normal(2,2,(2,2))
print(x)

tensor([[ 1.4035, -0.0589],
        [-1.1351,  0.7801]])


In [ ]:
random_seed = 1
torch.manual_seed(random_seed)
print(torch.rand(1))

tensor([0.7576])


In [ ]:
#random permutation of integers from 0 to 10
v = torch.randperm(10)
print(v)

tensor([8, 4, 6, 0, 5, 1, 3, 7, 2, 9])


In [ ]:
v = torch.randperm(5)
print(v)

tensor([2, 0, 3, 1, 4])


#Different datatypes

In [ ]:
#Create a tensor with unsigned integer type of 8 bit size
a = torch.tensor([100,200,2,3,4],dtype=torch.uint8)
#display tensor
print(a)
#display data type
print(a.dtype)

tensor([100, 200,   2,   3,   4], dtype=torch.uint8)
torch.uint8


In [ ]:
#create a tensor with signed integer type of 8 bits size
a = torch.tensor([100,0,-2,3,4],dtype=torch.int8)
print(a)


tensor([100,   0,  -2,   3,   4], dtype=torch.int8)


In [ ]:
b= torch.tensor([100,200,-2,-5,4],dtype=torch.uint8)
print(b)

tensor([100, 200, 254, 251,   4], dtype=torch.uint8)


In [ ]:
a = torch.tensor([100,200,20000,3,-4],dtype=torch.int16)
b = torch.tensor([100,200,20000,3,-4],dtype=torch.int16)
print(a)
print(b)

tensor([  100,   200, 20000,     3,    -4], dtype=torch.int16)
tensor([  100,   200, 20000,     3,    -4], dtype=torch.int16)


In [ ]:
#Create a tensor with floating point type of 32 bits size
a = torch.tensor([100,1.2,56.6,-99.3],dtype=torch.float32)
print(a)

tensor([100.0000,   1.2000,  56.6000, -99.3000])


In [ ]:
#element_size()*8 bits
a[0].element_size()*8

32

In [ ]:
#Create a tensor with floating point type of 64 bits size
a = torch.tensor([100,1.2,56.6,-99.3],dtype=torch.float64)
print(a)

tensor([100.0000,   1.2000,  56.6000, -99.3000], dtype=torch.float64)


In [ ]:
#element_size()*8 bits
a[0].element_size()*8

64

In [ ]:
#Creating a complex tensor
a = torch.tensor([1+2j,2+3j],dtype=torch.cfloat)
print(a)
print(a.dtype)
print(a[0].element_size()*8)

tensor([1.+2.j, 2.+3.j])
torch.complex64
64


In [ ]:
#Tensor with bool type
a = torch.tensor([100,200,0,3,4],dtype=torch.bool)
print(a)
print(a.dtype)
print(a[0].element_size()*8)

tensor([ True,  True, False,  True,  True])
torch.bool
8


In [ ]:
a = torch.tensor([[1,1],[0,1],[0,0]],dtype=torch.bool)
print(a)
print(a.dtype)
print(a[0].element_size()*8)

tensor([[ True,  True],
        [False,  True],
        [False, False]])
torch.bool
8


#Operations with constant

In [ ]:
a = torch.Tensor([5])
b = torch.Tensor([[5,5],[1,1]])
print("Multiplication with constant")
print(f"5xa: {5*a}")
print(f"5xb: {5*b}")

Multiplication with constant
5xa: tensor([25.])
5xb: tensor([[25., 25.],
        [ 5.,  5.]])


In [ ]:
print("Addition with constant")
print(f"5+a: {5+a}")
print(f"5+b: {5+b}")

Addition with constant
5+a: tensor([10.])
5+b: tensor([[10., 10.],
        [ 6.,  6.]])


In [ ]:
print("Division by constant")
print(f"a/5: {a/5}")
print(f"b/5: {b/5}")

Division by constant
a/5: tensor([1.])
b/5: tensor([[1.0000, 1.0000],
        [0.2000, 0.2000]])


#Element wise operations

In [ ]:
a = torch.Tensor([5,6])
b = torch.Tensor([1,2])
print(f"Addition:{a+b}")
print(f"Subtraction: {a-b}")
print(f"Multiplication: {a*b}")
print(f"Division: {a/b}")

Addition:tensor([6., 8.])
Subtraction: tensor([4., 4.])
Multiplication: tensor([ 5., 12.])
Division: tensor([5., 3.])


In [ ]:
#Bitwise operations
a = torch.tensor([[0,1],[1,0]],dtype=torch.bool)
b = torch.tensor([[0,1],[1,1]],dtype=torch.bool)
print(f"a and b: {torch.bitwise_and(a,b)}")
print(f"a or b: {torch.bitwise_or(a,b)}")
print(f"a xor b: {torch.bitwise_xor(a,b)}")
print(f"notb: {torch.bitwise_not(b)}")

a and b: tensor([[False,  True],
        [ True, False]])
a or b: tensor([[False,  True],
        [ True,  True]])
a xor b: tensor([[False, False],
        [False,  True]])
notb: tensor([[ True, False],
        [False, False]])


In [ ]:
#Shift operations
a = torch.tensor([[4]])
print(f"Bitwise left shift:{torch.bitwise_left_shift(a,1)}")


Bitwise left shift:tensor([[8]])


In [ ]:
a = torch.tensor([[4,2]])
print(f"Bitwise left shift:{torch.bitwise_left_shift(a,1)}")

Bitwise left shift:tensor([[8, 4]])


In [ ]:
a = torch.tensor([[32,15]])
print(f"Bitwise right shift:{torch.bitwise_right_shift(a,2)}")

Bitwise right shift:tensor([[8, 3]])


#Matrix Multiplication

In [ ]:
a = torch.Tensor([5,2])
b = torch.Tensor([2,3])
c = torch.matmul(a,b)
print(c)

tensor(16.)


In [ ]:
print(f"The size of a is: {a.size()}")
print(f"The size of b is: {b.size()}")
print(f"The size of c is: {c.size()}")
print(f"Type of c is: {type(c)}")

The size of a is: torch.Size([2])
The size of b is: torch.Size([2])
The size of c is: torch.Size([])
Type of c is: <class 'torch.Tensor'>


In [ ]:
a = torch.Tensor([[5,2]])
b = torch.Tensor([[2,3]])
c = torch.matmul(a,b)
print(c)
print(f"The size of a is: {a.size()}")
print(f"The size of b is: {b.size()}")
print(f"The size of c is: {c.size()}")
print(f"Type of c is: {type(c)}")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)

In [ ]:
a = torch.Tensor([[5,2]])
b = torch.Tensor([[2],[3]])
c = torch.matmul(a,b)
print(c)
print(f"The size of a is: {a.size()}")
print(f"The size of b is: {b.size()}")
print(f"The size of c is: {c.size()}")
print(f"Type of c is: {type(c)}")

tensor([[16.]])
The size of a is: torch.Size([1, 2])
The size of b is: torch.Size([2, 1])
The size of c is: torch.Size([1, 1])
Type of c is: <class 'torch.Tensor'>


In [ ]:
a = torch.Tensor([[5,2],[5,5]])
b = torch.Tensor([[5,5],[1,1]])
c = torch.matmul(a,b)
print(c)
print(f"The size of a is: {a.size()}")
print(f"The size of b is: {b.size()}")
print(f"The size of c is: {c.size()}")
print(f"Type of c is: {type(c)}")

tensor([[27., 27.],
        [30., 30.]])
The size of a is: torch.Size([2, 2])
The size of b is: torch.Size([2, 2])
The size of c is: torch.Size([2, 2])
Type of c is: <class 'torch.Tensor'>


In [ ]:
a = torch.Tensor([[[5,2],[5,5]]])
b = torch.Tensor([[5,5],[1,1]])
c = torch.matmul(a,b)
print(c)
print(f"The size of a is: {a.size()}")
print(f"The size of b is: {b.size()}")
print(f"The size of c is: {c.size()}")
print(f"Type of c is: {type(c)}")

tensor([[[27., 27.],
         [30., 30.]]])
The size of a is: torch.Size([1, 2, 2])
The size of b is: torch.Size([2, 2])
The size of c is: torch.Size([1, 2, 2])
Type of c is: <class 'torch.Tensor'>


In [ ]:
a = torch.Tensor([[[5,2],[5,5]],
                  [[5,5],[5,5]]
                  ])
b = torch.Tensor([[5,5],[1,1]])
c = torch.matmul(a,b)
print(c)
print(f"The size of a is: {a.size()}")
print(f"The size of b is: {b.size()}")
print(f"The size of c is: {c.size()}")
print(f"Type of c is: {type(c)}")

tensor([[[27., 27.],
         [30., 30.]],

        [[30., 30.],
         [30., 30.]]])
The size of a is: torch.Size([2, 2, 2])
The size of b is: torch.Size([2, 2])
The size of c is: torch.Size([2, 2, 2])
Type of c is: <class 'torch.Tensor'>


#Matrix inversion

In [ ]:
x = torch.Tensor([[5]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.inverse(x)
print(f"The inversion of x: {y}")
print(torch.matmul(x,y))

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1, 1])
The dimension of x is: 2
The inversion of x: tensor([[0.2000]])
tensor([[1.]])


In [ ]:
x = torch.Tensor([[5,5],[5,6]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.inverse(x)
print(f"The inversion of x: {y}")
print(torch.matmul(x,y))

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([2, 2])
The dimension of x is: 2
The inversion of x: tensor([[ 1.2000, -1.0000],
        [-1.0000,  1.0000]])
tensor([[1., 0.],
        [0., 1.]])


In [ ]:
x = torch.Tensor([[[5,5],[5,6]],
                  [[5,5],[5,6]]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.inverse(x)
print(f"The inversion of x: {y}")
print(torch.matmul(x,y))

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([2, 2, 2])
The dimension of x is: 3
The inversion of x: tensor([[[ 1.2000, -1.0000],
         [-1.0000,  1.0000]],

        [[ 1.2000, -1.0000],
         [-1.0000,  1.0000]]])
tensor([[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]])


#Transpose of matrix

In [ ]:
x = torch.Tensor([[4,3],[5,6]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.transpose(x,0,1)
print(f"The transpose of x: {y}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([2, 2])
The dimension of x is: 2
The transpose of x: tensor([[4., 5.],
        [3., 6.]])


In [ ]:
x = torch.Tensor([[4,3],[5,6]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.transpose(x,1,0)
print(f"The transpose of x: {y}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([2, 2])
The dimension of x is: 2
The transpose of x: tensor([[4., 5.],
        [3., 6.]])


In [ ]:
x = torch.Tensor([[4,3],[5,6],[7,8]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.transpose(x,1,0)
print(f"The transpose of x: {y}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([3, 2])
The dimension of x is: 2
The transpose of x: tensor([[4., 5., 7.],
        [3., 6., 8.]])


In [ ]:
x = torch.Tensor([[4,3],[5,6],[7,8]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.transpose(x,0,1)
print(f"The transpose of x: {y}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([3, 2])
The dimension of x is: 2
The transpose of x: tensor([[4., 5., 7.],
        [3., 6., 8.]])


In [ ]:
x = torch.Tensor([[[4,3],[5,6]]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.transpose(x,1,2)
print(f"The transpose of x: {y}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1, 2, 2])
The dimension of x is: 3
The transpose of x: tensor([[[4., 5.],
         [3., 6.]]])


In [ ]:
x = torch.Tensor([[[4,3],[5,6]],
                  [[1,2],[8,9]]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")
y = torch.transpose(x,2,1)
print(f"The transpose of x: {y}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([2, 2, 2])
The dimension of x is: 3
The transpose of x: tensor([[[4., 5.],
         [3., 6.]],

        [[1., 8.],
         [2., 9.]]])


#Determinant of matrix

In [3]:
x = torch.Tensor([[5]])
print(x)
print(torch.det(x))

tensor([[5.]])
tensor(5.)


In [4]:
x = torch.Tensor([[5,1],
                  [1,5]])
print(x)
print(torch.det(x))

tensor([[5., 1.],
        [1., 5.]])
tensor(24.)


In [5]:
x = torch.Tensor([[[5,1],[1,5]],
                  [[1,2],[6,3]]])
print(x)
print(torch.det(x))

tensor([[[5., 1.],
         [1., 5.]],

        [[1., 2.],
         [6., 3.]]])
tensor([24., -9.])


#Indexing and Slicing

In [6]:
x = torch.Tensor([5])
x[0]

tensor(5.)

In [7]:
x[0][0]

IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

In [9]:
x = torch.Tensor([[5]])
print(x[0])
print(f"The type of x[0] is {type(x[0])}")
print(f"The dimension of x[0] is {x[0].ndim}")

tensor([5.])
The type of x[0] is <class 'torch.Tensor'>
The dimension of x[0] is 1


In [11]:
x = torch.Tensor([[5]])
print(x[0][0])
print(f"The type of x[0][0] is {type(x[0][0])}")
print(f"The dimension of x[0][0] is {x[0][0].ndim}")

tensor(5.)
The type of x[0][0] is <class 'torch.Tensor'>
The dimension of x[0][0] is 0


In [12]:
x = torch.Tensor([[5,1,3],
                  [5,6,2],
                  [7,8,9]])
print(x[0][0])
print(x[0][1])
print(x[0][:2])
print(x[0][-2:])



tensor(5.)
tensor(1.)
tensor([5., 1.])
tensor([1., 3.])


In [17]:
x = torch.Tensor([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[10,11,12],
                  [13,14,15],
                  [16,17,18]],
                  [[21,22,23],
                   [24,25,26],
                   [27,28,29]]])

In [18]:
print(x)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[21., 22., 23.],
         [24., 25., 26.],
         [27., 28., 29.]]])


In [19]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [20]:
x[1]

tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [21]:
x[2]

tensor([[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]])

In [22]:
x[:2]

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [23]:
x[-2:]

tensor([[[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[21., 22., 23.],
         [24., 25., 26.],
         [27., 28., 29.]]])

In [24]:
x[0][1]

tensor([4., 5., 6.])

#Broadcasting

In [25]:
x = torch.Tensor([5,5])
y = torch.Tensor([1])
print(x)
print(y)
print(x+y)

tensor([5., 5.])
tensor([1.])
tensor([6., 6.])


In [28]:
x = torch.Tensor([[5,5],[0,0]])
y = torch.Tensor([1])
print(x)
print(y)
print(x+y)

tensor([[5., 5.],
        [0., 0.]])
tensor([1.])
tensor([[6., 6.],
        [1., 1.]])


In [30]:
x = torch.Tensor([[5,5],[0,0]])
y = torch.Tensor([1,2])
print(x)
print(y)
print("\n")
print(x+y)

tensor([[5., 5.],
        [0., 0.]])
tensor([1., 2.])


tensor([[6., 7.],
        [1., 2.]])


In [31]:
x = torch.Tensor([[[5,5],
                  [0,0]],
                  [[0,2],
                   [0,3]]])
y = torch.Tensor([1,2])
print(x)
print(y)
print("\n")
print(x+y)

tensor([[[5., 5.],
         [0., 0.]],

        [[0., 2.],
         [0., 3.]]])
tensor([1., 2.])


tensor([[[6., 7.],
         [1., 2.]],

        [[1., 4.],
         [1., 5.]]])


In [32]:
x = torch.Tensor([[[5,5],
                  [0,0]],
                  [[0,2],
                   [0,3]]])
y = torch.Tensor([[1,2],[2,2]])
print(x)
print(y)
print("\n")
print(x+y)

tensor([[[5., 5.],
         [0., 0.]],

        [[0., 2.],
         [0., 3.]]])
tensor([[1., 2.],
        [2., 2.]])


tensor([[[6., 7.],
         [2., 2.]],

        [[1., 4.],
         [2., 5.]]])


#Reshape

In [33]:
v = torch.arange(9)
print(v)
w = v.view(3,3)
print(w)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [35]:
x = torch.randint(0,10,(4,3))
x

tensor([[7, 3, 2],
        [6, 4, 8],
        [1, 2, 8],
        [0, 7, 1]])

In [36]:
y = x.view(2,6)
print(y)

tensor([[7, 3, 2, 6, 4, 8],
        [1, 2, 8, 0, 7, 1]])


In [37]:
y = x.view(6,2)
print(y)

tensor([[7, 3],
        [2, 6],
        [4, 8],
        [1, 2],
        [8, 0],
        [7, 1]])


#Squueze and Unsqueeze

In [38]:
x = torch.Tensor([[[5,5,6,6,7,8]]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1, 1, 6])
The dimension of x is: 3


In [40]:
y = torch.squeeze(x)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([5., 5., 6., 6., 7., 8.])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([6])
The dimension of y is: 1


In [41]:
x = torch.Tensor([[[5,5,6,6,7,8],
                   [9,9,9,9,9,9]]])
print(f"The type of x is: {type(x)}")
print(f"The size of x is: {x.size()}")
print(f"The dimension of x is: {x.ndim}")

The type of x is: <class 'torch.Tensor'>
The size of x is: torch.Size([1, 2, 6])
The dimension of x is: 3


In [42]:
y = torch.squeeze(x)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([[5., 5., 6., 6., 7., 8.],
        [9., 9., 9., 9., 9., 9.]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([2, 6])
The dimension of y is: 2


In [46]:
x = torch.rand(1,2,3,1)
print(x)

tensor([[[[0.5111],
          [0.2637],
          [0.2116]],

         [[0.2512],
          [0.2692],
          [0.5311]]]])


In [48]:
y = torch.squeeze(x)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([[0.5111, 0.2637, 0.2116],
        [0.2512, 0.2692, 0.5311]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([2, 3])
The dimension of y is: 2


In [49]:
y = torch.squeeze(x,dim=0)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([[[0.5111],
         [0.2637],
         [0.2116]],

        [[0.2512],
         [0.2692],
         [0.5311]]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([2, 3, 1])
The dimension of y is: 3


In [50]:
y = torch.squeeze(x,dim=1)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([[[[0.5111],
          [0.2637],
          [0.2116]],

         [[0.2512],
          [0.2692],
          [0.5311]]]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([1, 2, 3, 1])
The dimension of y is: 4


In [51]:
y = torch.squeeze(x,dim=2)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([[[[0.5111],
          [0.2637],
          [0.2116]],

         [[0.2512],
          [0.2692],
          [0.5311]]]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([1, 2, 3, 1])
The dimension of y is: 4


In [52]:
y = torch.squeeze(x,dim=3)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")

tensor([[[0.5111, 0.2637, 0.2116],
         [0.2512, 0.2692, 0.5311]]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([1, 2, 3])
The dimension of y is: 3


In [57]:
y=torch.rand(2,3)
print(y)
print(f"The type of y is: {type(y)}")
print(f"The size of y is: {y.size()}")
print(f"The dimension of y is: {y.ndim}")


tensor([[0.0751, 0.9631, 0.7369],
        [0.5999, 0.8485, 0.0912]])
The type of y is: <class 'torch.Tensor'>
The size of y is: torch.Size([2, 3])
The dimension of y is: 2


In [58]:
z = torch.unsqueeze(y,0)
print(z)
print(f"The type of z is: {type(z)}")
print(f"The size of z is: {z.size()}")
print(f"The dimension of z is: {z.ndim}")

tensor([[[0.0751, 0.9631, 0.7369],
         [0.5999, 0.8485, 0.0912]]])
The type of z is: <class 'torch.Tensor'>
The size of z is: torch.Size([1, 2, 3])
The dimension of z is: 3


In [59]:
z = torch.unsqueeze(y,1)
print(z)
print(f"The type of z is: {type(z)}")
print(f"The size of z is: {z.size()}")
print(f"The dimension of z is: {z.ndim}")

tensor([[[0.0751, 0.9631, 0.7369]],

        [[0.5999, 0.8485, 0.0912]]])
The type of z is: <class 'torch.Tensor'>
The size of z is: torch.Size([2, 1, 3])
The dimension of z is: 3


In [60]:
z = torch.unsqueeze(y,2)
print(z)
print(f"The type of z is: {type(z)}")
print(f"The size of z is: {z.size()}")
print(f"The dimension of z is: {z.ndim}")

tensor([[[0.0751],
         [0.9631],
         [0.7369]],

        [[0.5999],
         [0.8485],
         [0.0912]]])
The type of z is: <class 'torch.Tensor'>
The size of z is: torch.Size([2, 3, 1])
The dimension of z is: 3


In [62]:
z = torch.unsqueeze(z,3)
print(z)
print(f"The type of z is: {type(z)}")
print(f"The size of z is: {z.size()}")
print(f"The dimension of z is: {z.ndim}")

tensor([[[[0.0751]],

         [[0.9631]],

         [[0.7369]]],


        [[[0.5999]],

         [[0.8485]],

         [[0.0912]]]])
The type of z is: <class 'torch.Tensor'>
The size of z is: torch.Size([2, 3, 1, 1])
The dimension of z is: 4


#Concatenate and Stack

In [63]:
x = torch.Tensor([5,5])
y = torch.Tensor([3,3])
print(torch.cat((x,y),0))

tensor([5., 5., 3., 3.])


In [64]:
x = torch.Tensor([5,5])
y = torch.Tensor([3,3])
print(torch.cat((x,y),1))

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [65]:
x = torch.Tensor([[5,5]])
y = torch.Tensor([[3,3]])
print(torch.cat((x,y),1))

tensor([[5., 5., 3., 3.]])


In [66]:
x = torch.Tensor([[5,5]])
y = torch.Tensor([[3,3]])
print(torch.cat((x,y),0))

tensor([[5., 5.],
        [3., 3.]])


In [67]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print("\n")
print(y)

tensor([[0.0636, 0.4825],
        [0.2195, 0.3184]])


tensor([[0.1264, 0.1337],
        [0.4445, 0.2871]])


In [69]:
print(torch.stack((x,y)))

tensor([[[0.0636, 0.4825],
         [0.2195, 0.3184]],

        [[0.1264, 0.1337],
         [0.4445, 0.2871]]])


#Reorganize the data element

In [70]:
v = torch.arange(9)
w = v.view(3,3)
print(v)
print(w)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [71]:
r= torch.chunk(v,3)
print(r)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]))


In [72]:
r= torch.split(v,3)
print(r)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]))


In [73]:
r= torch.split(v,2)
print(r)

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8]))


In [75]:
r= torch.split(v,1)
print(v)
print(r)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
(tensor([0]), tensor([1]), tensor([2]), tensor([3]), tensor([4]), tensor([5]), tensor([6]), tensor([7]), tensor([8]))


In [76]:
v = torch.rand(3,4)
print(v)
r = torch.chunk(v,3)
print(r)
s = torch.split(v,3)
print(s)

tensor([[0.3235, 0.3774, 0.1562, 0.7488],
        [0.9719, 0.6423, 0.0508, 0.8146],
        [0.9408, 0.2468, 0.3457, 0.7288]])
(tensor([[0.3235, 0.3774, 0.1562, 0.7488]]), tensor([[0.9719, 0.6423, 0.0508, 0.8146]]), tensor([[0.9408, 0.2468, 0.3457, 0.7288]]))
(tensor([[0.3235, 0.3774, 0.1562, 0.7488],
        [0.9719, 0.6423, 0.0508, 0.8146],
        [0.9408, 0.2468, 0.3457, 0.7288]]),)


In [77]:
v = torch.rand(3,4)
print(v)
r = torch.chunk(v,3)
print(r)
s = torch.split(v,1)
print(s)

tensor([[0.3511, 0.3398, 0.8912, 0.3821],
        [0.6562, 0.6408, 0.8628, 0.2887],
        [0.9027, 0.6128, 0.4422, 0.4669]])
(tensor([[0.3511, 0.3398, 0.8912, 0.3821]]), tensor([[0.6562, 0.6408, 0.8628, 0.2887]]), tensor([[0.9027, 0.6128, 0.4422, 0.4669]]))
(tensor([[0.3511, 0.3398, 0.8912, 0.3821]]), tensor([[0.6562, 0.6408, 0.8628, 0.2887]]), tensor([[0.9027, 0.6128, 0.4422, 0.4669]]))


#Numpy and PyTorch Tensor

In [78]:
import numpy as np
x = np.array([2,3])
print(x)
print(f"Type of x: {type(x)}")
y = torch.from_numpy(x)
print(y)
print(f"Type of x: {type(y)}")

[2 3]
Type of x: <class 'numpy.ndarray'>
tensor([2, 3])
Type of x: <class 'torch.Tensor'>


In [79]:
a = torch.Tensor([2,3])
print(a)
print(f"Type of a: {type(a)}")
b = a.numpy()
print(b)
print(f"Type of x: {type(b)}")

tensor([2., 3.])
Type of a: <class 'torch.Tensor'>
[2. 3.]
Type of x: <class 'numpy.ndarray'>


#Operation on complex numbers

In [80]:
a = torch.tensor([1+2j], dtype=torch.cfloat)
b = torch.tensor([2+3j], dtype=torch.cfloat)
print('The real part of a: \n',a.real)
print('\nThe imaginary part of a: \n',a.imag)
print('\n The absolute value of a: \n ',a.abs())
print('\n The angle of a: \n ',a.angle())
print('\n Result of addition of complex numbers:\n',a+b)
print('\n Result of subtraction of complex numbers:\n',a-b)
print('\n Result of multiplication of complex numbers:\n',a*b)
print('\n Result of division of complex numbers:\n',a/b)

The real part of a: 
 tensor([1.])

The imaginary part of a: 
 tensor([2.])

 The absolute value of a: 
  tensor([2.2361])

 The angle of a: 
  tensor([1.1071])

 Result of addition of complex numbers:
 tensor([3.+5.j])

 Result of subtraction of complex numbers:
 tensor([-1.-1.j])

 Result of multiplication of complex numbers:
 tensor([-4.+7.j])

 Result of division of complex numbers:
 tensor([0.6154+0.0769j])
